"""Constants for HA Rhythm."""

DOMAIN = "ha_rhythm"
VERSION = "1.0.0"

CONF_AI_PROVIDER = "ai_provider"
CONF_AI_KEY = "ai_key"
CONF_AI_BASE_URL = "ai_base_url"
CONF_AI_MODEL = "ai_model"
CONF_SCAN_DAYS = "scan_days"

DEFAULT_PROVIDER = "groq"
DEFAULT_SCAN_DAYS = 21

PROVIDERS = ["groq", "openrouter", "ollama", "lmstudio", "openai", "anthropic", "custom"]

PROVIDER_PRESETS = {
    "groq": {
        "base_url": "https://api.groq.com/openai/v1",
        "model": "llama-3.3-70b-versatile",
    },
    "openrouter": {
        "base_url": "https://openrouter.ai/api/v1",
        "model": "meta-llama/llama-3.3-70b-instruct:free",
    },
    "ollama": {
        "base_url": "http://localhost:11434/v1",
        "model": "llama3.2:latest",
        "api_key": "ollama",
    },
    "lmstudio": {
        "base_url": "http://localhost:1234/v1",
        "model": "local-model",
        "api_key": "lm-studio",
    },
    "openai": {
        "base_url": "https://api.openai.com/v1",
        "model": "gpt-4o-mini",
    },
}

PATTERN_SYSTEM_PROMPT = """You are a Home Assistant automation expert.
You receive a verified behavioral pattern extracted from real home sensor data.
The pattern data is factual — do not invent or assume anything beyond what is given.

Respond with valid JSON in exactly this format:
{
  "explanation": "One sentence describing what the person actually does (max 120 chars)",
  "worth_automating": true,
  "confidence": "high",
  "automation": {
    "id": "rhythm_<snake_case_id>",
    "alias": "Rhythm: <short name>",
    "description": "Auto-generated by HA Rhythm from observed behavior",
    "trigger": [ ... ],
    "condition": [ ... ],
    "action": [ ... ],
    "mode": "single"
  }
}

confidence values: "high" (>80% consistency), "medium" (60-80%), "low" (<60%)
worth_automating: false if the pattern is trivial or already covered by default HA behavior

Rules for the automation YAML:
- Use entity_id values exactly as provided — never guess or modify them
- For time-based patterns use platform: time trigger with the window_start time
- If weekday_only is true, add a condition: weekday [mon,tue,wed,thu,fri]
- If weekend_only is true, add a condition: weekday [sat,sun]
- If correlated_with has entries, use the trigger entity as trigger
- Keep actions minimal: just turn on/off the entity
- All automation IDs must start with "rhythm_" """
